"""Shared configuration for Auto-Schematic."""

IMAGE_SIZE = 64
MIN_AREA = 15
ERROR_THRESHOLD = 0.08
AMBIGUITY_THRESHOLD = 0.15
MSE_NOISE_THRESHOLD = 0.15
MSE_NOISE_THRESHOLD_LOOSE = 0.15
ENABLE_FLIPS = False
ENABLE_TTA_ROTATIONS = True
MAHALANOBIS_REG_EPS = 1e-3
MAHALANOBIS_QUANTILE = 0.99
MAHALANOBIS_THRESHOLD_SCALE = 1.05
MIN_CONFIDENCE = 0.65
PROTO_Q = 0.995
PROTO_SCALE = 1.2
