"""Shared configuration for Auto-Schematic."""

IMAGE_SIZE = 64
MIN_AREA = 15
ERROR_THRESHOLD = 0.08
AMBIGUITY_THRESHOLD = 0.15
MSE_NOISE_THRESHOLD = 0.15
MAHALANOBIS_REG_EPS = 1e-3
MAHALANOBIS_QUANTILE = 0.99
MAHALANOBIS_THRESHOLD_SCALE = 1.05
